import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { favicon } from "../multitenant-images";
import links from "../fontlinks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: favicon,
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://example.com/',
    title: 'Create Next App',
    description: 'Generated by create next app',
    siteName: 'Next.js',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      {/* Aquí se incluyen los enlaces CSS manualmente */}
      {links.map((value, i) => (
        <link key={i} href={value} rel="stylesheet" />
      ))}
    </head>
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      {children}
    </body>
  </html>
  );
}
